-- Adds the expanded Oculi demo catalog used by the map, feed, search, uploads,
-- place detail pages, and photographer profiles.
insert into public.oculi_demo_catalog_items (kind, item_id, payload, updated_at)
select 'user', value->>'id', value, now()
from jsonb_array_elements($oculi_user$[
  {"id":"user-zoe","name":"Zoe Kim","username":"@zoekim.photo","avatarUrl":"/generated/avatar-zoe-kim.png","bio":"Gardens, quiet museums, and soft botanical light.","homeArea":"Inner Richmond","followerCount":1740,"followingCount":298},
  {"id":"user-marcus","name":"Marcus Lee","username":"@marcusframes","avatarUrl":"/generated/avatar-marcus-lee.png","bio":"Transit lines, long shadows, and downtown geometry.","homeArea":"SoMa","followerCount":1325,"followingCount":221},
  {"id":"user-ava","name":"Ava Thompson","username":"@ava.coast","avatarUrl":"/generated/avatar-ava-thompson.png","bio":"Coastal hikes, beaches, and weather that makes a frame.","homeArea":"Pacifica","followerCount":2480,"followingCount":355,"isInfluencer":true},
  {"id":"user-diego","name":"Diego Alvarez","username":"@diego.nights","avatarUrl":"/generated/avatar-diego-alvarez.png","bio":"Night color, neon, diners, and handheld street sets.","homeArea":"Lower Haight","followerCount":1168,"followingCount":409}
]$oculi_user$::jsonb) as value
on conflict (kind, item_id) do update
set payload = excluded.payload,
    updated_at = excluded.updated_at;

insert into public.oculi_demo_catalog_items (kind, item_id, payload, updated_at)
select 'place', value->>'id', value, now()
from jsonb_array_elements($oculi_place$[
  {"id":"japanese-tea-garden","areaId":"sf","name":"Japanese Tea Garden","description":"Layered garden paths, arched bridges, maples, and soft shade for calm detail shots.","lat":37.7703,"lng":-122.4705,"fuzzyLocationLabel":"Golden Gate Park garden paths","navigationAddress":"Japanese Tea Garden, 75 Hagiwara Tea Garden Dr, San Francisco, CA","timCurated":true,"saveCount":538,"recentActivityScore":84,"bestTimes":["Morning","Overcast days","Spring bloom"],"tags":["garden","architecture","portraits","details"],"coverPhotoUrl":"/generated/japanese-tea-garden.png"},
  {"id":"de-young-observation-deck","areaId":"sf","name":"de Young Observation Deck","description":"Museum geometry, glass reflections, and treetop-to-city views from a public deck.","lat":37.7715,"lng":-122.4687,"fuzzyLocationLabel":"Golden Gate Park museum tower","navigationAddress":"de Young Museum, 50 Hagiwara Tea Garden Dr, San Francisco, CA","timCurated":false,"saveCount":446,"recentActivityScore":72,"bestTimes":["Daylight","Late afternoon","Clear afternoons"],"tags":["architecture","skyline","reflections","museum"],"coverPhotoUrl":"/generated/de-young-observation-deck.png"},
  {"id":"muir-woods","areaId":"sf","name":"Muir Woods","description":"Redwood scale, filtered forest light, boardwalk lines, and misty morning texture.","lat":37.8954,"lng":-122.5809,"fuzzyLocationLabel":"Public redwood boardwalks","navigationAddress":"Muir Woods National Monument, Mill Valley, CA","timCurated":true,"saveCount":702,"recentActivityScore":75,"bestTimes":["Morning","Foggy mornings","Overcast days"],"tags":["forest","landscape","trail","moody"],"coverPhotoUrl":"/generated/muir-woods.png"},
  {"id":"mori-point","areaId":"sf","name":"Mori Point","description":"Coastal bluffs, winding trails, wildflowers, and Pacific sunset layers.","lat":37.6138,"lng":-122.4869,"fuzzyLocationLabel":"Pacifica public bluff trails","navigationAddress":"Mori Point, Mori Point Rd, Pacifica, CA","timCurated":false,"saveCount":487,"recentActivityScore":70,"bestTimes":["Sunset","Golden hour","Spring bloom"],"tags":["coast","trail","landscape","wildflowers"],"coverPhotoUrl":"/generated/mori-point.png"},
  {"id":"ferry-plaza-market","areaId":"sf","name":"Ferry Plaza Market","description":"Produce color, vendor motion, bay-facing light, and easy documentary frames.","lat":37.7956,"lng":-122.3933,"fuzzyLocationLabel":"Ferry Building plaza","navigationAddress":"Ferry Plaza Farmers Market, 1 Ferry Building, San Francisco, CA","timCurated":false,"saveCount":365,"recentActivityScore":82,"bestTimes":["Morning","Daylight","Rainy evenings"],"tags":["street","food","color","waterfront"],"coverPhotoUrl":"/generated/ferry-plaza-market.png"},
  {"id":"16th-avenue-tiles","areaId":"sf","name":"16th Avenue Tiled Steps","description":"Mosaic stairs, ocean-facing neighborhood views, and punchy color for portraits.","lat":37.7563,"lng":-122.4739,"fuzzyLocationLabel":"Inner Sunset tiled stairway","navigationAddress":"16th Avenue Tiled Steps, 16th Ave, San Francisco, CA","timCurated":false,"saveCount":429,"recentActivityScore":73,"bestTimes":["Morning","Late afternoon","Overcast days"],"tags":["stairs","color","portraits","architecture"],"coverPhotoUrl":"/generated/16th-avenue-tiles.png"},
  {"id":"haight-ashbury","areaId":"sf","name":"Haight-Ashbury Storefronts","description":"Vintage signage, saturated facades, sidewalk portraits, and layered street color.","lat":37.7692,"lng":-122.4481,"fuzzyLocationLabel":"Haight Street corridor","navigationAddress":"Haight St & Ashbury St, San Francisco, CA","timCurated":false,"saveCount":398,"recentActivityScore":78,"bestTimes":["Daylight","Late afternoon","Night"],"tags":["street","color","portraits","night"],"coverPhotoUrl":"/generated/haight-ashbury.png"},
  {"id":"treasure-island","areaId":"sf","name":"Treasure Island Skyline","description":"Long skyline compression, bay reflections, and clean blue-hour city layers.","lat":37.823,"lng":-122.3708,"fuzzyLocationLabel":"Public waterfront viewpoints","navigationAddress":"Treasure Island, San Francisco, CA","timCurated":true,"saveCount":624,"recentActivityScore":81,"bestTimes":["Blue hour","Night","Sunset"],"tags":["skyline","waterfront","night","telephoto"],"coverPhotoUrl":"/generated/treasure-island.png"}
]$oculi_place$::jsonb) as value
on conflict (kind, item_id) do update
set payload = excluded.payload,
    updated_at = excluded.updated_at;

insert into public.oculi_demo_catalog_items (kind, item_id, payload, updated_at)
select 'photo', value->>'id', value, now()
from jsonb_array_elements($oculi_photo$[
  {"id":"photo-29","placeId":"japanese-tea-garden","userId":"user-zoe","imageUrl":"/generated/photo-29-soft-shade-under-the-maples-made-the-bridge-color-feel-painted-in.png","caption":"Soft shade under the maples made the bridge color feel painted in.","locationLabel":"Japanese Tea Garden","metadataText":"50mm, open shade","shotAtTimeOfDay":"Morning","tags":["garden","details","portraits"],"createdAt":"2026-07-07T16:10:00.000Z","likeCount":139},
  {"id":"photo-30","placeId":"japanese-tea-garden","userId":"user-isha","imageUrl":"/generated/photo-30-the-paths-stack-up-nicely-if-you-wait-for-a-clean-opening.png","caption":"The paths stack up nicely if you wait for a clean opening.","locationLabel":"Japanese Tea Garden","metadataText":"85mm, garden shade","shotAtTimeOfDay":"Overcast days","tags":["garden","architecture","calm"],"createdAt":"2026-07-07T15:42:00.000Z","likeCount":118},
  {"id":"photo-31","placeId":"de-young-observation-deck","userId":"user-marcus","imageUrl":"/generated/photo-31-glass-trees-and-city-grid-all-line-up-from-the-tower.png","caption":"Glass, trees, and city grid all line up from the tower.","locationLabel":"de Young Observation Deck","metadataText":"35mm, polarizer","shotAtTimeOfDay":"Daylight","tags":["architecture","skyline","reflections"],"createdAt":"2026-07-07T00:28:00.000Z","likeCount":93},
  {"id":"photo-32","placeId":"de-young-observation-deck","userId":"user-zoe","imageUrl":"/generated/photo-32-late-sun-turned-the-copper-skin-into-a-huge-reflector.png","caption":"Late sun turned the copper skin into a huge reflector.","locationLabel":"de Young Observation Deck","metadataText":"70mm, warm reflections","shotAtTimeOfDay":"Late afternoon","tags":["museum","architecture","golden hour"],"createdAt":"2026-07-06T23:36:00.000Z","likeCount":107},
  {"id":"photo-33","placeId":"muir-woods","userId":"user-ava","imageUrl":"/generated/photo-33-fog-sat-high-in-the-canopy-and-kept-the-boardwalk-highlights-gentle.png","caption":"Fog sat high in the canopy and kept the boardwalk highlights gentle.","locationLabel":"Muir Woods","metadataText":"24mm, mist","shotAtTimeOfDay":"Morning","tags":["forest","fog","trail"],"createdAt":"2026-07-06T16:05:00.000Z","likeCount":204},
  {"id":"photo-34","placeId":"muir-woods","userId":"user-nora","imageUrl":"/generated/photo-34-use-the-rail-as-a-leading-line-and-the-trees-do-the-rest.png","caption":"Use the rail as a leading line and the trees do the rest.","locationLabel":"Muir Woods","metadataText":"35mm, low contrast","shotAtTimeOfDay":"Overcast days","tags":["forest","landscape","moody"],"createdAt":"2026-07-06T15:22:00.000Z","likeCount":167},
  {"id":"photo-35","placeId":"mori-point","userId":"user-ava","imageUrl":"/generated/photo-35-wildflowers-in-front-pacific-haze-in-back-wind-everywhere.png","caption":"Wildflowers in front, Pacific haze in back, wind everywhere.","locationLabel":"Mori Point","metadataText":"35mm, coastal wind","shotAtTimeOfDay":"Golden hour","tags":["coast","wildflowers","sunset"],"createdAt":"2026-07-05T03:58:00.000Z","likeCount":145},
  {"id":"photo-36","placeId":"mori-point","userId":"user-sam","imageUrl":"/generated/photo-36-the-trail-curve-gives-the-bluff-a-clean-sense-of-scale.png","caption":"The trail curve gives the bluff a clean sense of scale.","locationLabel":"Mori Point","metadataText":"70mm, sunset haze","shotAtTimeOfDay":"Sunset","tags":["coast","trail","landscape"],"createdAt":"2026-07-05T03:17:00.000Z","likeCount":112},
  {"id":"photo-37","placeId":"ferry-plaza-market","userId":"user-marcus","imageUrl":"/generated/photo-37-color-blocks-everywhere-before-the-plaza-got-crowded.png","caption":"Color blocks everywhere before the plaza got crowded.","locationLabel":"Ferry Plaza Market","metadataText":"35mm, morning market","shotAtTimeOfDay":"Morning","tags":["street","food","color"],"createdAt":"2026-07-04T17:08:00.000Z","likeCount":86},
  {"id":"photo-38","placeId":"ferry-plaza-market","userId":"user-lena","imageUrl":"/generated/photo-38-the-bayside-light-wraps-the-stalls-better-than-you-expect.png","caption":"The bayside light wraps the stalls better than you expect.","locationLabel":"Ferry Plaza Market","metadataText":"50mm, daylight","shotAtTimeOfDay":"Daylight","tags":["waterfront","street","market"],"createdAt":"2026-07-04T18:14:00.000Z","likeCount":94},
  {"id":"photo-39","placeId":"16th-avenue-tiles","userId":"user-zoe","imageUrl":"/generated/photo-39-overcast-kept-the-mosaic-saturated-without-harsh-stair-shadows.png","caption":"Overcast kept the mosaic saturated without harsh stair shadows.","locationLabel":"16th Avenue Tiled Steps","metadataText":"35mm, overcast","shotAtTimeOfDay":"Overcast days","tags":["stairs","color","portraits"],"createdAt":"2026-07-03T20:12:00.000Z","likeCount":121},
  {"id":"photo-40","placeId":"16th-avenue-tiles","userId":"user-jules","imageUrl":"/generated/photo-40-great-portrait-color-if-you-frame-tight-and-avoid-the-midday-shine.png","caption":"Great portrait color if you frame tight and avoid the midday shine.","locationLabel":"16th Avenue Tiled Steps","metadataText":"85mm, shade portrait","shotAtTimeOfDay":"Late afternoon","tags":["portraits","color","stairs"],"createdAt":"2026-07-03T23:32:00.000Z","likeCount":104},
  {"id":"photo-41","placeId":"haight-ashbury","userId":"user-diego","imageUrl":"/generated/photo-41-every-block-has-a-different-color-temperature-after-sunset.png","caption":"Every block has a different color temperature after sunset.","locationLabel":"Haight-Ashbury Storefronts","metadataText":"35mm, handheld","shotAtTimeOfDay":"Night","tags":["street","color","night"],"createdAt":"2026-07-03T05:05:00.000Z","likeCount":132},
  {"id":"photo-42","placeId":"haight-ashbury","userId":"user-eli","imageUrl":"/generated/photo-42-late-afternoon-gives-the-painted-storefronts-enough-shadow-to-separate.png","caption":"Late afternoon gives the painted storefronts enough shadow to separate.","locationLabel":"Haight-Ashbury Storefronts","metadataText":"50mm, late sun","shotAtTimeOfDay":"Late afternoon","tags":["street","portraits","color"],"createdAt":"2026-07-02T23:55:00.000Z","likeCount":98},
  {"id":"photo-43","placeId":"treasure-island","userId":"user-diego","imageUrl":"/generated/photo-43-blue-hour-held-just-long-enough-for-the-bay-reflections.png","caption":"Blue hour held just long enough for the bay reflections.","locationLabel":"Treasure Island Skyline","metadataText":"Tripod, 3s exposure","shotAtTimeOfDay":"Blue hour","tags":["skyline","night","waterfront"],"createdAt":"2026-07-02T04:38:00.000Z","likeCount":186},
  {"id":"photo-44","placeId":"treasure-island","userId":"user-marcus","imageUrl":"/generated/photo-44-long-lens-compresses-the-towers-into-one-clean-layer.png","caption":"Long lens compresses the towers into one clean layer.","locationLabel":"Treasure Island Skyline","metadataText":"135mm, tripod","shotAtTimeOfDay":"Night","tags":["skyline","telephoto","night"],"createdAt":"2026-07-01T05:10:00.000Z","likeCount":158}
]$oculi_photo$::jsonb) as value
on conflict (kind, item_id) do update
set payload = excluded.payload,
    updated_at = excluded.updated_at;
